version: '3'

services:
  frontend:
    image: node:18-alpine
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - API_ENDPOINT=http://backend:8000/api
      - LLM_API_KEY=${OPENAI_API_KEY}
    networks:
      - ai-territory-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    networks:
      - ai-territory-network

networks:
  ai-territory-network:
    driver: bridge